
services:

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  productsDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD_PRODUCT}
      ACCEPT_EULA: Y
    container_name: productsDb
    ports:
      - "${PRODUCT_DB_PORT}:1433"
    networks:
      - backend

  productservice:
    build:
      context: ./productService
    container_name: productservice
    ports:
      - "${PRODUCT_SERVICE_PORT}:8080"
    networks:
      - backend
    depends_on:
      - productsDb
      - rabbitmq

  operationsDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD_OPERATIONS}
      ACCEPT_EULA: Y
    container_name: operationsDb
    ports:
      - "${OPERATIONS_DB_PORT}:1433"
    networks:
      - backend

  operationsservice:
    build:
      context: ./operationService
    container_name: operationsservice
    ports:
      - "${OPERATIONS_SERVICE_PORT}:8080"
    networks:
      - backend
    depends_on:
      - operationsDb
      - rabbitmq

  stocksDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD_STOCK}
      ACCEPT_EULA: Y
    container_name: stocksDb
    ports:
      - "${STOCK_DB_PORT}:1433"
    networks:
      - backend

  stocksservice:
    build:
      context: ./stockService
    container_name: stocksservice
    ports:
      - "${STOCK_SERVICE_PORT}:8080"
    networks:
      - backend
    depends_on:
      - stocksDb
      - rabbitmq

  apigateway:
    build:
      context: ./apiGateway
    container_name: apigateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - productservice
      - operationsservice
      - stocksservice
    networks:
      - backend

networks:
  backend:
    driver: bridge
